services:
  # Hub Container - Redis API + Redis DB
  # Clients will connect directly to this service on port 8001
  hub:
    container_name: hub
    build:
      context: ../..  # Root of the monorepo
      dockerfile: ./apps/mock-env/Dockerfile.hub
    ports:
      - "8001:8001"  # Redis API
      - "6380:6379"  # Redis DB (mapped to different host port)
    environment:
      - PYTHONPATH=/app:/core  # Ensure core modules can be imported
    networks:
      - redis-network
    volumes:
      - ../../hub:/app/hub  # Mount local hub directory to /app/hub in container
      - ../../core:/app/core  # Mount shared core code'
    profiles:
      - dev

  # Worker Containers
  worker1:
    container_name: worker1
    build:
      context: ../..  # Root of the monorepo
      dockerfile: ./apps/mock-env/Dockerfile.worker
    environment:
      - MACHINE_ID=worker1
      - NUM_WORKERS=3
      - REDIS_API_HOST=hub
      - REDIS_API_PORT=8001
      - PYTHONPATH=/app:/core  # Ensure core modules can be imported
    networks:
      - redis-network
    depends_on:
      - hub
    volumes:
      - ../../worker:/app/worker  # Mount local worker directory to /app/worker in container
      - ../../core:/app/core  # Mount shared core code
    profiles:
      - dev

  worker2:
    container_name: worker2
    build:
      context: ../..  # Root of the monorepo
      dockerfile: ./apps/mock-env/Dockerfile.worker
    environment:
      - MACHINE_ID=worker2
      - NUM_WORKERS=4
      - REDIS_API_HOST=hub
      - REDIS_API_PORT=8001
      - PYTHONPATH=/app:/core  # Ensure core modules can be imported
    networks:
      - redis-network
    depends_on:
      - hub
    volumes:
      - ../../worker:/app/worker  # Mount local worker directory to /app/worker in container
      - ../../core:/app/core  # Mount shared core code
    profiles:
      - dev

  worker3:
    container_name: worker3
    build:
      context: ../..  # Root of the monorepo
      dockerfile: ./apps/mock-env/Dockerfile.worker
    environment:
      - MACHINE_ID=worker3
      - NUM_WORKERS=3
      - REDIS_API_HOST=hub
      - REDIS_API_PORT=8001
      - PYTHONPATH=/app:/core  # Ensure core modules can be imported
    networks:
      - redis-network
    depends_on:
      - hub
    volumes:
      - ../../worker:/app/worker  # Mount local worker directory to /app/worker in container
      - ../../core:/app/core  # Mount shared core code
    profiles:
      - dev

  worker4:
    container_name: worker4
    build:
      context: ../..  # Root of the monorepo
      dockerfile: ./apps/mock-env/Dockerfile.worker
    environment:
      - MACHINE_ID=worker4
      - NUM_WORKERS=4
      - REDIS_API_HOST=hub
      - REDIS_API_PORT=8001
      - PYTHONPATH=/app:/core  # Ensure core modules can be imported
    networks:
      - redis-network
    depends_on:
      - hub
    volumes:
      - ../../worker:/app/worker  # Mount local worker directory to /app/worker in container
      - ../../core:/app/core  # Mount shared core code
    profiles:
      - dev

networks:
  redis-network:
    driver: bridge
