name: Build and Push Hub Docker Image

on:
  push:
    branches: [ main, master ]
    paths:
      - 'hub/**'
      - 'core/**'
      - 'apps/prod_redis_server/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version info
        id: version
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          VERSION="${TIMESTAMP}-${COMMIT_SHA}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/prod_redis_server/Dockerfile
          push: true
          tags: |
            emprops/redis_server:latest
            emprops/redis_server:${{ steps.version.outputs.version }}
          cache-from: type=registry,ref=emprops/redis_server:buildcache
          cache-to: type=registry,ref=emprops/redis_server:buildcache,mode=max

      # Hub workflow only builds and pushes Docker images
      # No GitHub release is created for the hub server
      # Only the worker package creates GitHub releases with assets
